### ISSUE TITLE
Use sklearn instead of tsne

### ISSUE THREAD

**Issue by glucksfall** [KwanLab/Autometa#106]
Hello,

Could you consider the use of sklearn instead of tsne? https://pypi.org/project/tsne/
I'm having trouble trying to install tsne under CentOS6 and 7 and we could not provide support to run the Autometa docker because of SLURM https://slurm.schedmd.com/containers.html

I could help to modify the code and propose a PR.

Best regards,
Thank you.

**Comment by WiscEvan** [comment]
Hello glucksfall,

Thank you for your comment. As a matter of fact, we have sklearn available in our dev branch and we hope to release this soon. Although, we have noticed a difference in performance between the sklearn tsne implementation and the tsne implementation you have linked to.

Others have had difficulty installing tsne in the past. What are you using to manage your environment? I would recommend conda.


I have been able to install tsne with conda using the following commands:

```bash
# Create env
conda create -n py2 "python==2.7"
# Activate env
conda activate py2
# install tsne (w/dependencies)
conda install -c anaconda scikit-learn atlas cython -y
conda update -c anaconda scikit-learn -y
conda install -c maxibor tsne -y
```

Otherwise, you could try out the kmers module on the `dev` branch.

This will first require cloning the repo and checking out the dev branch (as well as setting up your environment [[see here]](https://autometa.readthedocs.io/en/latest/install.html "Autometa conda install page")). Instructions for running the kmers module are located [here](https://autometa.readthedocs.io/en/latest/scripts/common/kmers.html "kmers standalone instructions").

```bash
# Clone Autometa repo
git clone https://github.com/KwanLab/Autometa.git
cd Autometa
git pull
git checkout dev
```
**Note:** I've noticed you have forked the repo, so you should be able to just check out the `dev` branch there, in which case you can ignore the cloning of the repo above.

```bash

# Set up conda env
conda create -n autometa "python>=3.7" --yes
conda install -n autometa -c bioconda -c conda-forge --yes \
    biopython \
    pandas \
    tqdm \
    numpy \
    scikit-learn \
    samtools \
    bedtools \
    bowtie2 \
    hmmer \
    prodigal \
    diamond \
    ndcctools \
    parallel \
    requests \
    umap-learn \
    tsne \
    && conda clean --all --yes

# Activate your autometa environment
conda activate autometa

# Now run kmers module with your data
# Note: you should be in the Autometa directory here.
python -m autometa.common.kmers --help
```

Let me know if this works for you.

Thanks again for your feedback!

**Comment by glucksfall** [comment]
Hello @WiscEvan,

Thank you for your feedback on this matter.

I will tell to the future user of Autometa about your instructions. My problem is that I will not use the software for my research, but rather how I make available the software to many users inside our computing infrastructure. I think the user could install Anaconda on his own and run the instructions (BTW, they work for python3.7, thanks). However, I prefer to control the environment in a "per server" basis and not "per user" (because we already have a software managing environments called 'module').

I have access to a server running ubuntu and there was no problem to install tsne and run the complete pipeline in the README. During the weekend, I changed the code to use sklearn instead of tsne and works under centOS6. In the case of performance, I think it is not a matter of concern since it took a half-day to complete the pipeline in the ubuntu server (16 CPUs) and 5 hours in centOS6 (30 CPUs). If in your experience, the software works correctly with sklearn, I will wait for the official release and tell the user to install anaconda3 on his own.

PS1: Sadly, the COVID pandemic delayed the decision to migrate all servers from centOS6 and 7 to Ubuntu 20.04.

PS2: I found this problem trying to install tsne with the instructions for `conda create -n py2 "python==2.7"`

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tsne -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']

Your python: python=2.7
```

**Comment by jason-c-kwan** [comment]
@glucksfall Just to add a few points:
1. @WiscEvan recently contributed to the tsne module, making it python 3 compliant. So you will have to install the previous version if you want to use Python 2.
2. The sklearn tsne gives different results to the tsne module, and I am not just talking about the non-determinalistic nature of tsne, but it looks completely different. Since the tsne module uses the reference implementation of BH-tSNE by Laurens van der Maatens (https://lvdmaaten.github.io/tsne/), I felt it was better to go with that one over sklearn.
