### ISSUE TITLE
Add support request template

### ISSUE THREAD

**Issue by WiscEvan** [KwanLab/Autometa#74]
From discussions with @KwanLab/autometa, decision has been made to construct a template for general users that are just requesting support.

Add template to ISSUE_TEMPLATE: `support_request.md`

Cover:
-  system requirements
- command used
- expected behavior.

**Comment by chanana** [comment]
Suggestions:

1. From [here](https://github.com/stevemao/github-issue-templates/blob/master/checklist/ISSUE_TEMPLATE.md)

Ask the user questions in the form of a checklist:

* [ ] Can you reproduce the problem in safe mode?
* [ ] Are you running the latest version?
* [ ] Did you check the debugging guide?
* [ ] Did you check the FAQs on Discuss?
* [ ] Are you reporting to the correct repository?
* [ ] Did you perform a cursory search? Possible link to lmgtfy.

-----------------------------

2. From [here](https://github.com/stevemao/github-issue-templates/blob/master/must-open-issue-before-pr/ISSUE_TEMPLATE.md)  

Hey there and thank you for using Issue Tracker!

Our project, as you've probably heard, is getting really popular and truth is we're getting a bit overwhelmed by the activity surrounding it. There are just too many issues for us to manage properly.

Do the checklist before filing an issue:

- Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.
- Have a usage question? Ask your question on StackOverflow. We use StackOverflow for usage question and GitHub for bugs.
- Have an idea for a feature? Post the feature request on Product Pains. It has a voting system to surface the important issues. GitHub issues should only be used for bugs.
- None of the above, create a bug report

Make sure to add all the information needed to understand the bug so that someone can help. If the info is missing we'll add the `Needs more information` label and close the issue until there is enough information.

- Provide a minimal code snippet / rnplay example that reproduces the bug.
- Provide screenshots where appropriate
- What's the version of React Native you're using?
- Does this occur on iOS, Android or both?
- Are you using Mac, Linux or Windows?
